config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#home'

  get 'about' => 'pages#about'

  resources :posts
  resources :tags, only: [:show]
  devise_scope :user do
     get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :user

    def all_tags
      self.tags.map(&:name).join(', ')
    end

    def all_tags=(names)
      self.tags = names.split(',').map do |name|
        Tag.where(name: name.strip).first_or_create!
      end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  def self.counts
   self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
 end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  has_many :posts

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  validate :validate_username

  def validate_username
  if User.where(email: username).exists?
    errors.add(:username, :invalid)
   end
  end

def self.find_first_by_auth_conditions(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  else
    if conditions[:username].nil?
      where(conditions).first
    else
      where(username: conditions[:username]).first
    end
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @posts = @posts.includes(:tags,:user)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
       redirect_to @post
     else
       render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
   params.require(:post).permit(:title,:summary, :body, :image, :all_tags)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f
      yield(tag,[index.round])
    end
  end
end

app/views/include/main/_notification.html.erb
      <% if notice %>
       <p class="notice alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
       <p class="alert alert-dungeon"><%= alert %></p>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Рецензист</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <style type="text/css">

.blog-header {
 line-height: 1;
 border-bottom: 1px solid #e5e5e5;
}

.blog-header-logo {
 font-family: "Playfair Display", Georgia, "Times New Roman", serif;
 font-size: 2.25rem;
}

.blog-header-logo:hover {
 text-decoration: none;
}

h1, h2, h3, h4, h5, h6 {
 font-family: "Playfair Display", Georgia, "Times New Roman", serif;
}

.display-4 {
 font-size: 2.5rem;
}
@media (min-width: 768px) {
 .display-4 {
   font-size: 3rem;
 }
}

.nav-scroller {
 position: relative;
 z-index: 2;
 height: 2.75rem;
 overflow-y: hidden;
}

.nav-scroller .nav {
 display: -webkit-box;
 display: -ms-flexbox;
 display: flex;
 -ms-flex-wrap: nowrap;
 flex-wrap: nowrap;
 padding-bottom: 1rem;
 margin-top: -1px;
 overflow-x: auto;
 text-align: center;
 white-space: nowrap;
 -webkit-overflow-scrolling: touch;
}

.nav-scroller .nav-link {
 padding-top: .75rem;
 padding-bottom: .75rem;
 font-size: .875rem;
}

.card-img-right {
 height: 100%;
 border-radius: 0 3px 3px 0;
}

.flex-auto {
 -ms-flex: 0 0 auto;
 -webkit-box-flex: 0;
 flex: 0 0 auto;
}

.h-250 { height: 250px; }
@media (min-width: 768px) {
 .h-md-250 { height: 250px; }
}

.border-top { border-top: 1px solid #e5e5e5; }
.border-bottom { border-bottom: 1px solid #e5e5e5; }

.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

/*
* Blog name and description
*/
.blog-title {
 margin-bottom: 0;
 font-size: 2rem;
 font-weight: 400;
}
.blog-description {
 font-size: 1.1rem;
 color: #999;
}

@media (min-width: 40em) {
 .blog-title {
   font-size: 3.5rem;
 }
}

/* Pagination */
.blog-pagination {
 margin-bottom: 4rem;
}
.blog-pagination > .btn {
 border-radius: 2rem;
}

/*
* Blog posts
*/
.blog-post {
 margin-bottom: 4rem;
}
.blog-post-title {
 margin-bottom: .25rem;
 font-size: 2.5rem;
}
.blog-post-meta {
 margin-bottom: 1.25rem;
 color: #999;
}

/*
* Footer
*/
.blog-footer {
 padding: 2.5rem 0;
 color: #999;
 text-align: center;
 background-color: #f9f9f9;
 border-top: .05rem solid #e5e5e5;
}
.blog-footer p:last-child {
 margin-bottom: 0;
}
      </style>
  </head>

  <body class="text-center">
    <div class="container">
      <header class="blog-header py-3">
        <div class="navbar-expand-lg navbar-light bg-light border-bottom shadow-sm d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">

          <nav class="navbar navbar-light my-0 mr-md-auto font-weight-normal">
            <img src="https://image.flaticon.com/icons/png/512/43/43212.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <a class="navbar-brand" <%= link_to "Рецензист", root_path%></a>
          </nav>

          <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark"<%= link_to "Все статьи", posts_path%></a>
            <a class="p-2 text-dark"><%= link_to "About", about_path%></a>

            <% if user_signed_in? %>
              <a class="p-2 text-dark" href="#"><%= link_to "Написать статью", new_post_path%></a>
              <a class="p-2 text-dark"><%= link_to 'Редактирование', edit_user_registration_path, class: "btn btn-outline-primary" %></a>
              <a class="p-2 text-dark"><%= link_to 'Выход', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %></a>
            <% else %>
              <a class="p-2 text-dark"><%= link_to 'Вход', new_user_session_path, class: "btn btn-outline-primary" %></a>
              <a class="p-2 text-dark"><%= link_to 'Регистрация', new_user_registration_path, class: "btn btn-outline-primary" %></a>
            <% end %>
          </nav>

    </header>
    <h1>О проэкте "Рецензист"</h1>
    </div>
</body>
</html>

app/views/posts/_post.html.erb
<article class="post">
  <section class= "post-head">
   <h5><%= post.title %></h5>
  </section>
   <p><%= post.user.username %></p>
  <time>
   <%= post.created_at.to_date.strftime("%d %B, %Y") %>
  </time>

    <br>
    <section class= "post-summary clearfix">
     <p><%= simple_format(post.summary) %></p>
    </section>
   <%= link_to "Читать полностью" , post_path(post), :class => 'btn btn-outline-primary' %>
   <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'badge badge-primary'}.join(' ') %>
    <hr>
  <br>
</article>

app/views/posts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Рецензист</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <style type="text/css">

.blog-header {
 line-height: 1;
 border-bottom: 1px solid #e5e5e5;
}

.blog-header-logo {
 font-family: "Playfair Display", Georgia, "Times New Roman", serif;
 font-size: 2.25rem;
}

.blog-header-logo:hover {
 text-decoration: none;
}

h1, h2, h3, h4, h5, h6 {
 font-family: "Playfair Display", Georgia, "Times New Roman", serif;
}

.display-4 {
 font-size: 2.5rem;
}
@media (min-width: 768px) {
 .display-4 {
   font-size: 3rem;
 }
}

.nav-scroller {
 position: relative;
 z-index: 2;
 height: 2.75rem;
 overflow-y: hidden;
}

.nav-scroller .nav {
 display: -webkit-box;
 display: -ms-flexbox;
 display: flex;
 -ms-flex-wrap: nowrap;
 flex-wrap: nowrap;
 padding-bottom: 1rem;
 margin-top: -1px;
 overflow-x: auto;
 text-align: center;
 white-space: nowrap;
 -webkit-overflow-scrolling: touch;
}

.nav-scroller .nav-link {
 padding-top: .75rem;
 padding-bottom: .75rem;
 font-size: .875rem;
}

.card-img-right {
 height: 100%;
 border-radius: 0 3px 3px 0;
}

.flex-auto {
 -ms-flex: 0 0 auto;
 -webkit-box-flex: 0;
 flex: 0 0 auto;
}

.h-250 { height: 250px; }
@media (min-width: 768px) {
 .h-md-250 { height: 250px; }
}

.border-top { border-top: 1px solid #e5e5e5; }
.border-bottom { border-bottom: 1px solid #e5e5e5; }

.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

/*
* Blog name and description
*/
.blog-title {
 margin-bottom: 0;
 font-size: 2rem;
 font-weight: 400;
}
.blog-description {
 font-size: 1.1rem;
 color: #999;
}

@media (min-width: 40em) {
 .blog-title {
   font-size: 3.5rem;
 }
}

/* Pagination */
.blog-pagination {
 margin-bottom: 4rem;
}
.blog-pagination > .btn {
 border-radius: 2rem;
}

/*
* Blog posts
*/
.blog-post {
 margin-bottom: 4rem;
}
.blog-post-title {
 margin-bottom: .25rem;
 font-size: 2.5rem;
}
.blog-post-meta {
 margin-bottom: 1.25rem;
 color: #999;
}

/*
* Footer
*/
.blog-footer {
 padding: 2.5rem 0;
 color: #999;
 text-align: center;
 background-color: #f9f9f9;
 border-top: .05rem solid #e5e5e5;
}
.blog-footer p:last-child {
 margin-bottom: 0;
}
      </style>

  </head>

  <body>

<div class="container">
  <header class="blog-header py-3">
    <div class="navbar-expand-lg navbar-light bg-light border-bottom shadow-sm d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">

      <nav class="navbar navbar-light my-0 mr-md-auto font-weight-normal">
        <img src="https://image.flaticon.com/icons/png/512/43/43212.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <a class="navbar-brand" <%= link_to "Рецензист", root_path%></a>
      </nav>

      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark"<%= link_to "Все статьи", posts_path%></a>
        <a class="p-2 text-dark"><%= link_to "About", about_path%></a>

        <% if user_signed_in? %>
          <a class="p-2 text-dark" href="#"><%= link_to "Написать статью", new_post_path%></a>
          <a class="p-2 text-dark">Добро пожаловать <%= current_user.username %></a>
          <a class="p-2 text-dark"><%= link_to 'Редактирование', edit_user_registration_path, class: "btn btn-outline-primary" %></a>
          <a class="p-2 text-dark"><%= link_to 'Выход', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %></a>
        <% else %>
          <a class="p-2 text-dark"><%= link_to 'Вход', new_user_session_path, class: "btn btn-outline-primary" %></a>
          <a class="p-2 text-dark"><%= link_to 'Регистрация', new_user_registration_path, class: "btn btn-outline-primary" %></a>
        <% end %>
      </nav>

</header>
<%= render 'include/main/notification' %>
</div>

<main class="container">
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
          <div class="col-md-6 px-0">
            <h1 class="display-6 font-italic">Литература — это самый приятный способ игнорировать жизнь.  Фернандо Пессоа</h1>
            <p class="lead my-3">Заберите у нас книги, и мы начинаем читать..</p>
            <p class="lead mb-0 text-white font-weight-bold"><%= link_to "Читать полностью" , post_path(2)%></p>
          </div>
        </div>
        <h2 class="blog-footer">Свежие рецензии</h2>

        <div class="row mb-2">
          <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
              <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-primary">Бойцовский клуб</strong>
                <h3 class="mb-0">
                  <a class="text-dark">Если не знаешь, чего хочешь, умрешь в куче того, чего не хотел.</a>
                </h3>
                <div class="mb-1 text-muted">17 августа 1996 г. Автор: Чак Паланик </div>
                 <p class="lead mb-0"><%= link_to "Читать полностью" , post_path(3)%></p>
                </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
              <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-primary">Так говорил Заратустра</strong>
                <h3 class="mb-0">
                  <a class="text-dark">Человек – это канат, натянутый между животным и сверхчеловеком, – канат над пропастью.</a>
                </h3>
                <div class="mb-1 text-muted">10 апреля 1885 г. Автор: Фридрих Ницше</div>
                <p class="lead mb-0"><%= link_to "Читать полностью" , post_path(4)%></p>
              </div>
            </div>
          </div>
        </div>

        <main role="main" class="container">
          <div class="row">
            <div class="col-md-8 blog-main">
              <h3 class="pb-3 mb-4 font-italic border-bottom">Пимер оформления для тех кто хочет стать автором</h3>

              <div class="blog-post">
                <h2 class="blog-post-title">Заголовок "Title"</h2>
                <p class="blog-post-meta">Дата публикации(генерируется автоматически)</p>
                <p>Заголовок включает в себя либо название книги, либо небольшая цитата из неё.</p>
                <hr>
                <blockquote>
                  <p>Так же не стоит забывать про картинку к посту.</p>
                </blockquote>

                <h2>Превью "Summary"</h2>
                <p>Краткое описание. Включает в себя первый текст, который увидет читатель.</p>
                <h3>Тело статьи "Body"</h3>
                <p>В тело мы записываем дату публкации и дальше зависит всё от вашей фантазии и красноречия.</p>
                <ul>
                  <li>Можно добавлять цитаты.</li>
                  <li>Критику других авторов.</li>
                  <li>Комментарии других людей</li>
                </ul>
                <p>Критерии для публикации.</p>
                <ol>
                  <li>От 500 слов</li>
                  <li>Уникальность должна быть больше 75%, можно проверить на этом <a href="https://text.ru/">сайте</a>.</li>
                  <li>"Слэнг" не приветствуется.</li>
                </ol>
                <p>Удачи в написании!</p>
              </div><!-- /.blog-post -->
            </div><!-- /.blog-main -->

            <aside class="col-md-4 blog-sidebar">
              <div class="p-3 mb-3 bg-light rounded">
                <h4 class="font-italic">О сайте</h4>
                <p class="mb-0">Сайт нацелен на <em>увеличение</em> количества читателей и заинтересовании людей в этом деле. Вы можете прочитать <em>краткую</em> рецензию и скачать её <em>по кнопке ниже.</em></p>
              </div>

              <div class="p-3">
                <h4 class="font-italic">Тэги</h4>
                <ol class="list-unstyled mb-0">

                  <% tag_cloud(Tag.counts) do |tag|%>
                   <%= link_to tag.name, tag_path(tag.name)%>
                  <%end%>

                </ol>
              </div>

              <div class="p-3">
                <h4 class="font-italic">Так же мы</h4>
                <ol class="list-unstyled">
                  <li><a href="https://t.me/joinchat/F2tX7Qa0cLVjYmUy">Telegram</a></li>
                  <li><a href="https://www.instagram.com/recenzist1613/">Instagram</a></li>
                </ol>
              </div>
            </aside><!-- /.blog-sidebar -->

          </div><!-- /.row -->

        </main>
      <footer class="blog-footer">
        <p><a href="#">Back to top</a></p>
      </footer>
    </main>
  </body>
    </html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Рецензист</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <style type="text/css">

.blog-header {
 line-height: 1;
 border-bottom: 1px solid #e5e5e5;
}

.blog-header-logo {
 font-family: "Playfair Display", Georgia, "Times New Roman", serif;
 font-size: 2.25rem;
}

.blog-header-logo:hover {
 text-decoration: none;
}

h1, h2, h3, h4, h5, h6 {
 font-family: "Playfair Display", Georgia, "Times New Roman", serif;
}

.display-4 {
 font-size: 2.5rem;
}
@media (min-width: 768px) {
 .display-4 {
   font-size: 3rem;
 }
}

.nav-scroller {
 position: relative;
 z-index: 2;
 height: 2.75rem;
 overflow-y: hidden;
}

.nav-scroller .nav {
 display: -webkit-box;
 display: -ms-flexbox;
 display: flex;
 -ms-flex-wrap: nowrap;
 flex-wrap: nowrap;
 padding-bottom: 1rem;
 margin-top: -1px;
 overflow-x: auto;
 text-align: center;
 white-space: nowrap;
 -webkit-overflow-scrolling: touch;
}

.nav-scroller .nav-link {
 padding-top: .75rem;
 padding-bottom: .75rem;
 font-size: .875rem;
}

.card-img-right {
 height: 100%;
 border-radius: 0 3px 3px 0;
}

.flex-auto {
 -ms-flex: 0 0 auto;
 -webkit-box-flex: 0;
 flex: 0 0 auto;
}

.h-250 { height: 250px; }
@media (min-width: 768px) {
 .h-md-250 { height: 250px; }
}

.border-top { border-top: 1px solid #e5e5e5; }
.border-bottom { border-bottom: 1px solid #e5e5e5; }

.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

/*
* Blog name and description
*/
.blog-title {
 margin-bottom: 0;
 font-size: 2rem;
 font-weight: 400;
}
.blog-description {
 font-size: 1.1rem;
 color: #999;
}

@media (min-width: 40em) {
 .blog-title {
   font-size: 3.5rem;
 }
}

/* Pagination */
.blog-pagination {
 margin-bottom: 4rem;
}
.blog-pagination > .btn {
 border-radius: 2rem;
}

/*
* Blog posts
*/
.blog-post {
 margin-bottom: 4rem;
}
.blog-post-title {
 margin-bottom: .25rem;
 font-size: 2.5rem;
}
.blog-post-meta {
 margin-bottom: 1.25rem;
 color: #999;
}

/*
* Footer
*/
.blog-footer {
 padding: 2.5rem 0;
 color: #999;
 text-align: center;
 background-color: #f9f9f9;
 border-top: .05rem solid #e5e5e5;
}
.blog-footer p:last-child {
 margin-bottom: 0;
}
      </style>
  </head>

  <body class="text-center">

    <div class="container">
      <header class="blog-header py-3">
        <div class="navbar-expand-lg navbar-light bg-light border-bottom shadow-sm d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">

          <nav class="navbar navbar-light my-0 mr-md-auto font-weight-normal">
            <img src="https://image.flaticon.com/icons/png/512/43/43212.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <a class="navbar-brand" <%= link_to "Рецензист", root_path%></a>
          </nav>

          <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark"<%= link_to "Все статьи", posts_path%></a>
            <a class="p-2 text-dark"><%= link_to "About", about_path%></a>

            <% if user_signed_in? %>
              <a class="p-2 text-dark" href="#"><%= link_to "Написать статью", new_post_path%></a>
              <a class="p-2 text-dark"><%= link_to 'Редактирование', edit_user_registration_path, class: "btn btn-outline-primary" %></a>
              <a class="p-2 text-dark"><%= link_to 'Выход', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %></a>
            <% else %>
              <a class="p-2 text-dark"><%= link_to 'Вход', new_user_session_path, class: "btn btn-outline-primary" %></a>
              <a class="p-2 text-dark"><%= link_to 'Регистрация', new_user_registration_path, class: "btn btn-outline-primary" %></a>
            <% end %>
          </nav>

    </header>

<h2><%= @post.title %> </h2>
    <%= @post.created_at.to_date.strftime("%d %B, %Y") %>
<hr>
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
<hr>
 <p><%= simple_format(@post.body) %></p>
<hr>
  <%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-outline-primary' %>
  <%= link_to "Удалить пост", post_path(@post), method: :delete, data:{confirm: "Хотите удалить статью?"}, :class => 'btn btn-outline-primary' %>
  <%= link_to 'Назад',:back, class: 'btn btn-outline-secondary'%>
  <footer class="blog-footer">
    <p>
      <a class="btn btn-outline-primary" href="#">Back to top</a>
    </p>
  </footer>
   <hr>
   </div>
</body>
</html>